using Aws.Cdk;
using AWS.Jsii.Runtime.Deputy;

namespace Aws.Cdk.CodePipeline
{
    /// <summary>An output artifact of an action. Artifacts can be used as input by some actions.</summary>
    [JsiiClass("@aws-cdk/codepipeline", "jsii$_aws_cdk_codepipeline$.Artifact", "[{\"name\":\"parent\",\"type\":{\"fqn\":\"jsii$_aws_cdk_codepipeline$.Action\"}},{\"name\":\"name\",\"type\":{\"primitive\":\"string\"}}]")]
    public class Artifact : Construct
    {
        public Artifact(Action parent, string name): base(new DeputyProps(new object[]{parent, name}))
        {
        }

        protected Artifact(ByRefValue reference): base(reference)
        {
        }

        protected Artifact(DeputyProps props): base(props)
        {
        }

        [JsiiProperty("name", "{\"primitive\":\"string\"}")]
        public override string Name
        {
            get => GetProperty<string>();
        }

        /// <summary>The artifact attribute for the name of the S3 bucket where the artifact is stored.</summary>
        [JsiiProperty("bucketName", "{\"fqn\":\"jsii$_aws_cdk_codepipeline$.ArtifactAttribute\"}")]
        public virtual ArtifactAttribute BucketName
        {
            get => GetProperty<ArtifactAttribute>();
        }

        /// <summary>
        /// The artifact attribute for The name of the .zip file that contains the artifact that is
        /// generated by AWS CodePipeline, such as 1ABCyZZ.zip.
        /// </summary>
        [JsiiProperty("objectKey", "{\"fqn\":\"jsii$_aws_cdk_codepipeline$.ArtifactAttribute\"}")]
        public virtual ArtifactAttribute ObjectKey
        {
            get => GetProperty<ArtifactAttribute>();
        }

        /// <summary>
        /// The artifact attribute of the Amazon Simple Storage Service (Amazon S3) URL of the artifact,
        /// such as https://s3-us-west-2.amazonaws.com/artifactstorebucket-yivczw8jma0c/test/TemplateSo/1ABCyZZ.zip.
        /// </summary>
        [JsiiProperty("url", "{\"fqn\":\"jsii$_aws_cdk_codepipeline$.ArtifactAttribute\"}")]
        public virtual ArtifactAttribute Url
        {
            get => GetProperty<ArtifactAttribute>();
        }

        /// <summary>
        /// Returns an ArtifactPath for a file within this artifact.
        /// Output is in the form "&lt;artifact-name&gt;::&lt;file-name&gt;"
        /// </summary>
        /// <param name = "fileName">The name of the file</param>
        [JsiiMethod("subartifact", "{\"fqn\":\"jsii$_aws_cdk_codepipeline$.ArtifactPath\"}", "[{\"name\":\"fileName\",\"type\":{\"primitive\":\"string\"}}]")]
        public virtual ArtifactPath Subartifact(string fileName)
        {
            return InvokeMethod<ArtifactPath>(new object[]{fileName});
        }

        /// <summary>Returns a token for a value inside a JSON file within this artifact.</summary>
        /// <param name = "jsonFile">The JSON file name.</param>
        /// <param name = "keyName">The hash key.</param>
        [JsiiMethod("getParam", "{\"fqn\":\"jsii$_aws_cdk_codepipeline$.ArtifactGetParam\"}", "[{\"name\":\"jsonFile\",\"type\":{\"primitive\":\"string\"}},{\"name\":\"keyName\",\"type\":{\"primitive\":\"string\"}}]")]
        public virtual ArtifactGetParam GetParam(string jsonFile, string keyName)
        {
            return InvokeMethod<ArtifactGetParam>(new object[]{jsonFile, keyName});
        }

        /// <summary>Returns a string representation of this construct.</summary>
        [JsiiMethod("toString", "{\"primitive\":\"string\"}", "[]")]
        public override string ToString()
        {
            return InvokeMethod<string>(new object[]{});
        }
    }
}